spark.master                     spark://spark-master:7077
spark.driver.host                spark-master
spark.driver.memory              2g
spark.executor.cores             2
spark.executor.memory            2g
spark.eventLog.enabled           true
spark.eventLog.dir               file:///opt/spark/logs/events
spark.history.ui.port            18080
spark.python.worker.reuse        true

spark.executorEnv.CLASSPATH      /opt/hadoop/etc/hadoop:/opt/hadoop/share/hadoop/common/lib/*:/opt/hadoop/share/hadoop/common/*:/opt/hadoop/share/hadoop/hdfs/lib/*:/opt/hadoop/share/hadoop/hdfs/*
spark.executorEnv.JAVA_HOME      /usr/lib/jvm/java-17-openjdk-amd64
spark.executorEnv.HADOOP_CONF_DIR /opt/hadoop/etc/hadoop