spark.master                     spark://spark-master:7077
spark.driver.host                spark-master
spark.driver.memory              2g
spark.executor.cores             2
spark.executor.memory            2g
spark.eventLog.enabled           true
spark.eventLog.dir               file:///opt/spark/logs/events
spark.history.ui.port            18080
spark.python.worker.reuse        true